version: '3'

services: 
  web_adm_metas:
    image: nginx:mainline-alpine3.18-perl
    container_name: web_adm_metas
    restart: always
    environment:
      - TZ=America/Bogota
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./client/dist:/usr/share/nginx/html

  api_adm_metas:
    build: ./api
    container_name: api_adm_metas
    image: api_adm_metas:v.1.0
    environment:
      - TZ=America/Bogota
    restart: always
    ports:
      - "4000:4000"
