version: '3'

services: 
  web_adm_metas:
    image: nginx:mainline-alpine3.18-perl
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./client/dist:/usr/share/nginx/html

  api_adm_metas:
    build: ./server
    restart: always
    ports:
      - "4000:4000"
    container_name: api_adm_metas
